CREATE TABLE [dbo].[EventMatchScores2017]
(
    [EventCode] nvarchar(50) NOT NULL,
	[TournamentLevel] nvarchar(50) NOT NULL,
	[MatchNumber] int NOT NULL,
	[Alliance] nvarchar(50) NOT NULL,
    [Robot1Auto] nvarchar(50) NOT NULL,
    [Robot2Auto] nvarchar(50) NOT NULL,
    [Robot3Auto] nvarchar(50) NOT NULL,
    [AutoFuelLow] int NOT NULL,
    [AutoFuelHigh] int NOT NULL,
    [Rotor1Auto] BIT NOT NULL,
    [Rotor2Auto] BIT NOT NULL,
    [Rotor1Engaged] BIT NOT NULL,
    [Rotor2Engaged] BIT NOT NULL,
    [Rotor3Engaged] BIT NOT NULL,
    [Rotor4Engaged] BIT NOT NULL,
    [TeleopFuelLow] int NOT NULL,
    [TeleopFuelHigh] int NOT NULL,
    [TouchpadNear] nvarchar(50) NOT NULL,
    [TouchpadMiddle] nvarchar(50) NOT NULL,
    [TouchpadFar] nvarchar(50) NOT NULL,
    [KiloPaRankingPointAchieved] BIT NOT NULL,
    [RotorRankingPointAchieved] BIT NOT NULL,
    [FoulCount] int NOT NULL,
    [TechFoulCount] int NOT NULL,
    [AutoPoints] int NOT NULL,
    [AutoMobilityPoints] int NOT NULL,
    [AutoRotorPoints] int NOT NULL,
    [AutoFuelPoints] int NOT NULL,
    [TeleopPoints] int NOT NULL,
    [TeleopRotorPoints] int NOT NULL,
    [TeleopFuelPoints] int NOT NULL,
    [TeleopTakeoffPoints] int NOT NULL,
    [KilokPaBonusPoints] int NOT NULL,
    [RotorBonusPoints] int NOT NULL,
    [AdjustPoints] int NOT NULL,
    [FoulPoints] int NOT NULL,
    [TotalPoints] int NOT NULL,
	CONSTRAINT [PK_EventMatchScoresEventCode] PRIMARY KEY CLUSTERED ([EventCode] ASC, [TournamentLevel], [MatchNumber])
)
