//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.USFirst.Frc.Team4911.ScoutingDatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public string DistrictCode { get; set; }
        public string Name { get; set; }
        public int Season { get; set; }
    }
}
