//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.USFirst.Frc.Team4911.ScoutingDatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMatchScores2017
    {
        public string EventCode { get; set; }
        public string TournamentLevel { get; set; }
        public int MatchNumber { get; set; }
        public string Alliance { get; set; }
        public string Robot1Auto { get; set; }
        public string Robot2Auto { get; set; }
        public string Robot3Auto { get; set; }
        public int AutoFuelLow { get; set; }
        public int AutoFuelHigh { get; set; }
        public bool Rotor1Auto { get; set; }
        public bool Rotor2Auto { get; set; }
        public bool Rotor1Engaged { get; set; }
        public bool Rotor2Engaged { get; set; }
        public bool Rotor3Engaged { get; set; }
        public bool Rotor4Engaged { get; set; }
        public int TeleopFuelLow { get; set; }
        public int TeleopFuelHigh { get; set; }
        public string TouchpadNear { get; set; }
        public string TouchpadMiddle { get; set; }
        public string TouchpadFar { get; set; }
        public bool KiloPaRankingPointAchieved { get; set; }
        public bool RotorRankingPointAchieved { get; set; }
        public int FoulCount { get; set; }
        public int TechFoulCount { get; set; }
        public int AutoPoints { get; set; }
        public int AutoMobilityPoints { get; set; }
        public int AutoRotorPoints { get; set; }
        public int AutoFuelPoints { get; set; }
        public int TeleopPoints { get; set; }
        public int TeleopRotorPoints { get; set; }
        public int TeleopFuelPoints { get; set; }
        public int TeleopTakeoffPoints { get; set; }
        public int KilokPaBonusPoints { get; set; }
        public int RotorBonusPoints { get; set; }
        public int AdjustPoints { get; set; }
        public int FoulPoints { get; set; }
        public int TotalPoints { get; set; }
    }
}
