//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.USFirst.Frc.Team4911.ScoutingDatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMatchResult
    {
        public int Season { get; set; }
        public string EventCode { get; set; }
        public System.DateTime ActualStartTime { get; set; }
        public string TournamentLevel { get; set; }
        public int MatchNumber { get; set; }
        public System.DateTime PostResultTime { get; set; }
        public int ScoreRedFinal { get; set; }
        public int ScoreRedFoul { get; set; }
        public int ScoreRedAuto { get; set; }
        public int ScoreBlueFinal { get; set; }
        public int ScoreBlueFoul { get; set; }
        public int ScoreBlueAuto { get; set; }
    }
}
