//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.USFirst.Frc.Team4911.ScoutingDatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoutingDataShotAttempt
    {
        public int Id { get; set; }
        public int ScoutingDataId { get; set; }
        public byte AutonomousMode { get; set; }
        public int ShotAttempt { get; set; }
        public int ShotsMade { get; set; }
        public int ShotsMissed { get; set; }
        public int ShotDuration { get; set; }
        public string ShotLocation { get; set; }
        public Nullable<byte> WasDefended { get; set; }
    
        public virtual ScoutingDataMatch ScoutingDataMatch { get; set; }
    }
}
