//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.USFirst.Frc.Team4911.ScoutingDatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamNumber { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string City { get; set; }
        public string StateProv { get; set; }
        public string Country { get; set; }
        public string DistrictCode { get; set; }
        public int RookieYear { get; set; }
        public string RobotName { get; set; }
        public string WebSite { get; set; }
        public string SchoolName { get; set; }
        public string HomeCMP { get; set; }
    }
}
