CREATE PROCEDURE [dbo].[Insert_EventMatchScore2017]
(
    @EventCode nvarchar(max),
	@TournamentLevel nvarchar(max),
	@MatchNumber int,
    @Alliance nvarchar(max),
    @Robot1Auto nvarchar(max),
    @Robot2Auto nvarchar(max),
    @Robot3Auto nvarchar(max),
    @AutoFuelLow int,
    @AutoFuelHigh int,
    @Rotor1Auto BIT,
    @Rotor2Auto BIT,
    @Rotor1Engaged BIT,
    @Rotor2Engaged BIT,
    @Rotor3Engaged BIT,
    @Rotor4Engaged BIT,
    @TeleopFuelLow int,
    @TeleopFuelHigh int,
    @TouchpadNear nvarchar(max),
    @TouchpadMiddle nvarchar(max),
    @TouchpadFar nvarchar(max),
    @KiloPaRankingPointAchieved BIT,
    @RotorRankingPointAchieved BIT,
    @FoulCount int,
    @TechFoulCount int,
    @AutoPoints int,
    @AutoMobilityPoints int,
    @AutoRotorPoints int,
    @AutoFuelPoints int,
    @TeleopPoints int,
    @TeleopRotorPoints int,
    @TeleopFuelPoints int,
    @TeleopTakeoffPoints int,
    @KilokPaBonusPoints int,
    @RotorBonusPoints int,
    @AdjustPoints int,
    @FoulPoints int,
    @TotalPoints int
)
AS
BEGIN
	SET NOCOUNT ON;
	MERGE INTO [dbo].[EventMatchScores2017] AS T
	USING ( VALUES
		(
			@EventCode,
			@TournamentLevel,
			@MatchNumber,
			@Alliance,
			@Robot1Auto,
			@Robot2Auto,
			@Robot3Auto,
			@AutoFuelLow,
			@AutoFuelHigh,
			@Rotor1Auto,
			@Rotor2Auto,
			@Rotor1Engaged,
			@Rotor2Engaged,
			@Rotor3Engaged,
			@Rotor4Engaged,
			@TeleopFuelLow,
			@TeleopFuelHigh,
			@TouchpadNear,
			@TouchpadMiddle,
			@TouchpadFar,
			@KiloPaRankingPointAchieved,
			@RotorRankingPointAchieved,
			@FoulCount,
			@TechFoulCount,
			@AutoPoints,
			@AutoMobilityPoints,
			@AutoRotorPoints,
			@AutoFuelPoints,
			@TeleopPoints,
			@TeleopRotorPoints,
			@TeleopFuelPoints,
			@TeleopTakeoffPoints,
			@KilokPaBonusPoints,
			@RotorBonusPoints,
			@AdjustPoints,
			@FoulPoints,
			@TotalPoints
		)
	) 
	AS S 
	(
		EventCode,
		TournamentLevel,
		MatchNumber,
		Alliance,
		Robot1Auto,
		Robot2Auto,
		Robot3Auto,
		AutoFuelLow,
		AutoFuelHigh,
		Rotor1Auto,
		Rotor2Auto,
		Rotor1Engaged,
		Rotor2Engaged,
		Rotor3Engaged,
		Rotor4Engaged,
		TeleopFuelLow,
		TeleopFuelHigh,
		TouchpadNear,
		TouchpadMiddle,
		TouchpadFar,
		KiloPaRankingPointAchieved,
		RotorRankingPointAchieved,
		FoulCount,
		TechFoulCount,
		AutoPoints,
		AutoMobilityPoints,
		AutoRotorPoints,
		AutoFuelPoints,
		TeleopPoints,
		TeleopRotorPoints,
		TeleopFuelPoints,
		TeleopTakeoffPoints,
		KilokPaBonusPoints,
		RotorBonusPoints,
		AdjustPoints,
		FoulPoints,
		TotalPoints
	)
	ON T.EventCode = S.EventCode AND T.TournamentLevel = S.TournamentLevel AND T.MatchNumber = S.MatchNumber
		WHEN MATCHED THEN
		UPDATE SET
			Alliance = S.Alliance,
			Robot1Auto = S.Robot1Auto,
			Robot2Auto = S.Robot2Auto,
			Robot3Auto = S.Robot3Auto,
			AutoFuelLow = S.AutoFuelLow,
			AutoFuelHigh = S.AutoFuelHigh,
			Rotor1Auto = S.Rotor1Auto,
			Rotor2Auto = S.Rotor2Auto,
			Rotor1Engaged = S.Rotor1Engaged,
			Rotor2Engaged = S.Rotor2Engaged,
			Rotor3Engaged = S.Rotor3Engaged,
			Rotor4Engaged = S.Rotor4Engaged,
			TeleopFuelLow = S.TeleopFuelLow,
			TeleopFuelHigh = S.TeleopFuelHigh,
			TouchpadNear = S.TouchpadNear,
			TouchpadMiddle = S.TouchpadMiddle,
			TouchpadFar = S.TouchpadFar,
			KiloPaRankingPointAchieved= S.KiloPaRankingPointAchieved,
			RotorRankingPointAchieved = S.RotorRankingPointAchieved,
			FoulCount = S.FoulCount,
			TechFoulCount = S.TechFoulCount,
			AutoPoints = S.AutoPoints,
			AutoMobilityPoints = S.AutoMobilityPoints,
			AutoRotorPoints = S.AutoRotorPoints,
			AutoFuelPoints = S.AutoFuelPoints,
			TeleopPoints = S.TeleopPoints,
			TeleopRotorPoints = S.TeleopRotorPoints,
			TeleopFuelPoints = S.TeleopFuelPoints,
			TeleopTakeoffPoints = S.TeleopTakeoffPoints,
			KilokPaBonusPoints = S.KilokPaBonusPoints,
			RotorBonusPoints = S.RotorBonusPoints,
			AdjustPoints = S.AdjustPoints,
			FoulPoints = S.FoulPoints,
			TotalPoints = S.TotalPoints
		WHEN NOT MATCHED THEN
		INSERT 
		(
			EventCode,
			TournamentLevel,
			MatchNumber,
			Alliance,
			Robot1Auto,
			Robot2Auto,
			Robot3Auto,
			AutoFuelLow,
			AutoFuelHigh,
			Rotor1Auto,
			Rotor2Auto,
			Rotor1Engaged,
			Rotor2Engaged,
			Rotor3Engaged,
			Rotor4Engaged,
			TeleopFuelLow,
			TeleopFuelHigh,
			TouchpadNear,
			TouchpadMiddle,
			TouchpadFar,
			KiloPaRankingPointAchieved,
			RotorRankingPointAchieved,
			FoulCount,
			TechFoulCount,
			AutoPoints,
			AutoMobilityPoints,
			AutoRotorPoints,
			AutoFuelPoints,
			TeleopPoints,
			TeleopRotorPoints,
			TeleopFuelPoints,
			TeleopTakeoffPoints,
			KilokPaBonusPoints,
			RotorBonusPoints,
			AdjustPoints,
			FoulPoints,
			TotalPoints
		)
		VALUES
		(
			S.EventCode,
			S.TournamentLevel,
			S.MatchNumber,
			S.Alliance,
			S.Robot1Auto,
			S.Robot2Auto,
			S.Robot3Auto,
			S.AutoFuelLow,
			S.AutoFuelHigh,
			S.Rotor1Auto,
			S.Rotor2Auto,
			S.Rotor1Engaged,
			S.Rotor2Engaged,
			S.Rotor3Engaged,
			S.Rotor4Engaged,
			S.TeleopFuelLow,
			S.TeleopFuelHigh,
			S.TouchpadNear,
			S.TouchpadMiddle,
			S.TouchpadFar,
			S.KiloPaRankingPointAchieved,
			S.RotorRankingPointAchieved,
			S.FoulCount,
			S.TechFoulCount,
			S.AutoPoints,
			S.AutoMobilityPoints,
			S.AutoRotorPoints,
			S.AutoFuelPoints,
			S.TeleopPoints,
			S.TeleopRotorPoints,
			S.TeleopFuelPoints,
			S.TeleopTakeoffPoints,
			S.KilokPaBonusPoints,
			S.RotorBonusPoints,
			S.AdjustPoints,
			S.FoulPoints,
			S.TotalPoints
		);
END
RETURN 0
