//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.USFirst.Frc.Team4911.ScoutingService.DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMatchTeam
    {
        public int Season { get; set; }
        public string EventCode { get; set; }
        public int MatchNumber { get; set; }
        public int TeamNumber { get; set; }
        public string Station { get; set; }
        public bool Dq { get; set; }
    }
}
