//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.USFirst.Frc.Team4911.ScoutingService.DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRanking
    {
        public int Season { get; set; }
        public string EventCode { get; set; }
        public int TeamNumber { get; set; }
        public int DqCount { get; set; }
        public int MatchesPlayed { get; set; }
        public double QualAverage { get; set; }
        public int Rank { get; set; }
        public int Wins { get; set; }
        public int Losses { get; set; }
        public int Ties { get; set; }
        public double SortOrder1 { get; set; }
        public double SortOrder2 { get; set; }
        public double SortOrder3 { get; set; }
        public double SortOrder4 { get; set; }
        public double SortOrder5 { get; set; }
        public double SortOrder6 { get; set; }
    }
}
