//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.USFirst.Frc.Team4911.ScoutingService.DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoutingDataMatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScoutingDataMatch()
        {
            this.ScoutDataHopperAttempts = new HashSet<ScoutDataHopperAttempt>();
            this.ScoutingDataAutonomous = new HashSet<ScoutingDataAutonomou>();
            this.ScoutingDataEndGames = new HashSet<ScoutingDataEndGame>();
            this.ScoutingDataGearAttempts = new HashSet<ScoutingDataGearAttempt>();
            this.ScoutingDataPreGames = new HashSet<ScoutingDataPreGame>();
            this.ScoutingDataQualitatives = new HashSet<ScoutingDataQualitative>();
            this.ScoutingDataShotAttempts = new HashSet<ScoutingDataShotAttempt>();
            this.ScoutingDataTeleops = new HashSet<ScoutingDataTeleop>();
        }
    
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public int Season { get; set; }
        public string EventCode { get; set; }
        public int MatchNumber { get; set; }
        public int TeamNumber { get; set; }
        public string MatchLevel { get; set; }
        public string Station { get; set; }
        public string ScoutName { get; set; }
        public string ScoutingTeam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoutDataHopperAttempt> ScoutDataHopperAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoutingDataAutonomou> ScoutingDataAutonomous { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoutingDataEndGame> ScoutingDataEndGames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoutingDataGearAttempt> ScoutingDataGearAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoutingDataPreGame> ScoutingDataPreGames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoutingDataQualitative> ScoutingDataQualitatives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoutingDataShotAttempt> ScoutingDataShotAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoutingDataTeleop> ScoutingDataTeleops { get; set; }
    }
}
