//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.USFirst.Frc.Team4911.ScoutingService.DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoutingDataPreGame
    {
        public int Id { get; set; }
        public int ScoutingDataId { get; set; }
        public byte PreGameHasGear { get; set; }
        public byte PreGameHasFuel { get; set; }
        public byte PreGameHasPilot { get; set; }
        public byte PreGameUsesOwnRope { get; set; }
        public string PreGameRopeTouchPadPosition { get; set; }
        public string PreGameRobotPosition { get; set; }
    
        public virtual ScoutingDataMatch ScoutingDataMatch { get; set; }
    }
}
